name: flutter_zapateria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^4.2.0
  path_provider: ^2.0.15
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_map: ^7.0.2
  url_launcher: ^6.1.14

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.0
  google_fonts: ^6.2.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/imagen_default.jpg
